/**
 * `apps/mobile/scripts/gen-assets.mjs` produces the four icon/splash PNGs
 * (13.7-u); jest's `testMatch` is `src/**` and never sees the script itself
 * (`node:fs`/`node:child_process` are fine here — see `parity.test.ts` for
 * the same disk-reading technique — but production source under `src/`
 * still avoids Node built-ins, `tokens.test.ts`'s header explains why).
 *
 * Checked here, not by eyeballing a PNG: the files exist at the sizes
 * `app.config.ts` expects, the generator is dependency-free, its brand color
 * has not drifted from `theme/tokens.ts`, and re-running it reproduces the
 * committed bytes exactly (the script's own determinism claim).
 */
import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

import { COLORS } from '../theme/tokens';

const ROOT = process.cwd();
const ASSETS_DIR = join(ROOT, 'assets');
const SCRIPT = join(ROOT, 'scripts', 'gen-assets.mjs');

const EXPECTED_SIZES: Record<string, { width: number; height: number }> = {
  'icon.png': { width: 1024, height: 1024 },
  'adaptive-icon.png': { width: 1024, height: 1024 },
  'splash.png': { width: 1024, height: 1024 },
  'notification-icon.png': { width: 96, height: 96 },
};

/** IHDR's width/height are the first bytes after the 8-byte PNG signature. */
function pngSize(path: string): { width: number; height: number } {
  const buf = readFileSync(path);
  expect(buf.subarray(0, 8)).toEqual(Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]));
  expect(buf.toString('ascii', 12, 16)).toBe('IHDR');
  return { width: buf.readUInt32BE(16), height: buf.readUInt32BE(20) };
}

describe('generated app icon/splash assets (13.7-u)', () => {
  it.each(Object.entries(EXPECTED_SIZES))('%s exists at the expected size', (name, expected) => {
    const path = join(ASSETS_DIR, name);
    expect(existsSync(path)).toBe(true);
    expect(pngSize(path)).toEqual(expected);
  });

  it('is generated by a dependency-free script — no image library was added for it', () => {
    const manifest = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8')) as {
      dependencies: Record<string, string>;
      devDependencies: Record<string, string>;
    };
    const names = [...Object.keys(manifest.dependencies), ...Object.keys(manifest.devDependencies)];
    expect(names.some((name) => /png|canvas|sharp|jimp|image/i.test(name))).toBe(false);
  });

  it('draws in brand-500, matching theme/tokens.ts rather than a second hardcoded copy', () => {
    const script = readFileSync(SCRIPT, 'utf8');
    const match = script.match(/BRAND_500 = \[([^\]]+)\]/);
    expect(match).not.toBeNull();
    const [r, g, b] = match![1]!.split(',').map((byte) => Number.parseInt(byte.trim(), 16));
    const hex = `#${[r, g, b].map((n) => n!.toString(16).padStart(2, '0')).join('')}`;
    expect(hex).toBe(COLORS.light.brand500);
  });

  it('is deterministic: re-running the generator reproduces the committed bytes exactly', () => {
    const before = Object.fromEntries(
      Object.keys(EXPECTED_SIZES).map((name) => [name, readFileSync(join(ASSETS_DIR, name))]),
    );
    execFileSync(process.execPath, [SCRIPT], { stdio: 'pipe' });
    for (const name of Object.keys(EXPECTED_SIZES)) {
      expect(readFileSync(join(ASSETS_DIR, name)).equals(before[name]!)).toBe(true);
    }
  });
});
