/**
 * Knowledge source "Added by" (FR-MOD-06.3.3).
 *
 * `added_by` has lived on the schema and been written on every create path
 * since 198.1 (`knowledge-file.test.ts`), but no response ever returned it —
 * the column existed and the table column the PRD asks for (Name / Last
 * Updated / Added by / Actions) could not. This locks the resolved *name*
 * (never a raw account id) across every response that can produce a source:
 * list, single create, file upload and bulk import.
 */
import type { PrismaClient } from '@prisma/client';
import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest';
import { grantToken, ownerClient, seedFixtures, type Fixtures } from '../helpers/fixtures.js';
import { clearRateLimits, startTestServer, type TestServer } from '../helpers/server.js';

interface SourceView {
  id: string;
  added_by_name: string | null;
}

interface BulkRowView {
  status: 'imported' | 'skipped';
  added_by_name: string | null;
}

describe('knowledge source — added by (FR-MOD-06.3.3)', () => {
  let owner: PrismaClient;
  let server: TestServer;
  let fx: Fixtures;
  let agentIdA: string;

  const write = async () => ({
    authorization: `Bearer ${await grantToken(owner, {
      licenseId: fx.a.licenseId,
      organizationId: fx.a.organizationId,
      ownerId: fx.a.ownerAccountId,
      scopes: ['agents-bot--all:rw'],
    })}`,
  });

  beforeAll(async () => {
    owner = ownerClient();
    server = await startTestServer();
  });

  afterAll(async () => {
    await server.close();
    await owner.$disconnect();
  });

  beforeEach(async () => {
    fx = await seedFixtures(owner);
    await clearRateLimits(server.app);
    const agent = await owner.aiAgent.create({
      data: { licenseId: fx.a.licenseId, kind: 'ai_agent', name: 'Ada' },
      select: { id: true },
    });
    agentIdA = agent.id;
  });

  it('names the creator on POST /knowledge-sources', async () => {
    const headers = await write();
    const response = await server.post(
      '/knowledge-sources',
      { ai_agent_id: agentIdA, name: 'FAQ', type: 'faq', content: 'We ship worldwide.' },
      headers,
    );
    expect(response.statusCode).toBe(201);
    expect((response.json() as SourceView).added_by_name).toBe('Owner a');
  });

  it('names the creator on POST /knowledge-sources/file', async () => {
    const headers = await write();
    const response = await server.post(
      '/knowledge-sources/file',
      {
        ai_agent_id: agentIdA,
        filename: 'faq.txt',
        content_type: 'text/plain',
        data: Buffer.from('We ship worldwide.', 'utf8').toString('base64'),
      },
      headers,
    );
    expect(response.statusCode).toBe(201);
    expect((response.json() as SourceView).added_by_name).toBe('Owner a');
  });

  it('carries the same name through to GET /knowledge-sources', async () => {
    const headers = await write();
    const created = await server.post(
      '/knowledge-sources',
      { ai_agent_id: agentIdA, name: 'FAQ', type: 'faq', content: 'We ship worldwide.' },
      headers,
    );
    const sourceId = (created.json() as { id: string }).id;

    const list = (await server.get('/knowledge-sources', headers)).json() as {
      items: SourceView[];
    };
    expect(list.items.find((s) => s.id === sourceId)?.added_by_name).toBe('Owner a');
  });

  it('returns null, never a raw account id, for a source added by nothing an account resolves', async () => {
    // A bot/seed-created row: `added_by` was never set. The API must report
    // "unknown" as null, not leak the column's own absence as a bare id.
    const source = await owner.knowledgeSource.create({
      data: {
        aiAgentId: agentIdA,
        licenseId: fx.a.licenseId,
        type: 'faq',
        name: 'System note',
        content: 'Autogenerated.',
        status: 'ready',
        addedBy: null,
        updatedAt: new Date(),
      },
    });

    const headers = await write();
    const list = (await server.get('/knowledge-sources', headers)).json() as {
      items: SourceView[];
    };
    const found = list.items.find((s) => s.id === source.id);
    expect(found).toBeDefined();
    expect(found?.added_by_name).toBeNull();
  });

  it('carries the same name on an imported bulk row, and null on a skipped one', async () => {
    const headers = await write();
    const csv = [
      'name,type,content,source_url',
      'Refunds,faq,We refund within 30 days.,',
      ',bogus,,',
    ].join('\n');

    const response = await server.post(
      '/knowledge-sources/bulk',
      { ai_agent_id: agentIdA, csv },
      headers,
    );
    expect(response.statusCode).toBe(200);
    const body = response.json() as { results: BulkRowView[] };
    expect(body.results[0]).toMatchObject({ status: 'imported', added_by_name: 'Owner a' });
    expect(body.results[1]).toMatchObject({ status: 'skipped', added_by_name: null });
  });

  it('reports null on every row of a dry run — nothing was actually added', async () => {
    const headers = await write();
    const response = await server.post(
      '/knowledge-sources/bulk',
      {
        ai_agent_id: agentIdA,
        csv: ['name,type,content,source_url', 'Refunds,faq,We refund within 30 days.,'].join('\n'),
        dry_run: true,
      },
      headers,
    );
    expect(response.statusCode).toBe(200);
    const body = response.json() as { results: BulkRowView[] };
    expect(body.results[0]).toMatchObject({ status: 'imported', added_by_name: null });
  });
});
