-- Onboarding: first-run setup wizard + sample data (FR-MOD-00.4).
--
-- Signup creates an empty workspace — no groups, no website, no conversations.
-- Two license-level flags track first-run setup: `onboarding_completed_at` flips
-- once the owner finishes or skips the wizard (so it gates once for the whole
-- workspace), and `demo_seeded_at` records that the sample data exists (so the
-- seed never runs twice).

ALTER TABLE licenses
  ADD COLUMN onboarding_completed_at TIMESTAMPTZ,
  ADD COLUMN demo_seeded_at          TIMESTAMPTZ;

-- Sample data for one workspace.
--
-- Why SECURITY DEFINER rather than an ordinary `withTenant` insert: this lays
-- rows into several tables at once — an org-scoped `customers` row alongside
-- license-scoped chats/threads/events — as one atomic, reviewable unit that
-- takes the tenant ids explicitly and writes only those. It mirrors the `auth_*`
-- bootstrap functions: a small, named hole that answers one need. The isolation
-- guarantee is that every row it writes carries the passed-in ids and nothing
-- reads or writes another tenant's data; `onboarding.test.ts` pins that a demo
-- seeded for one workspace is invisible from another.
--
-- Idempotent via `demo_seeded_at`: a workspace already seeded (or whose owner
-- has since added their own data) keeps what it has and the call is a no-op.
-- The short chat/thread ids are generated by the caller (Crockford base32, the
-- one place the app owns the id format) and passed in.
CREATE OR REPLACE FUNCTION onboarding_seed_demo(
  p_license_id      BIGINT,
  p_organization_id UUID,
  p_owner_id        UUID,
  p_chat_id         TEXT,
  p_thread_id       TEXT
)
RETURNS TABLE (seeded BOOLEAN, canned INT, tags INT, customers INT, chats INT)
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_customer UUID        := gen_random_uuid();
  v_now      TIMESTAMPTZ := now();
  v_started  TIMESTAMPTZ := v_now - INTERVAL '6 minutes';
BEGIN
  -- Run once per workspace. Everything below is guarded by this flag, so a
  -- second call — or a workspace whose owner already has data — is left alone.
  IF (SELECT l.demo_seeded_at FROM licenses l WHERE l.id = p_license_id) IS NOT NULL THEN
    RETURN QUERY SELECT false, 0, 0, 0, 0;
    RETURN;
  END IF;

  -- Events are range-partitioned by month; ensure the current partition exists
  -- before inserting, exactly as the boot path does.
  PERFORM events_ensure_partition(v_now);

  -- Saved replies the owner can use straight away (#hello, #thanks, #hours).
  INSERT INTO canned_responses (id, license_id, scope, shortcut, text, updated_by, updated_at)
  VALUES
    (gen_random_uuid(), p_license_id, 'chat', 'hello',
     'Hi there! How can I help you today?', p_owner_id::text, v_now),
    (gen_random_uuid(), p_license_id, 'chat', 'thanks',
     'Thanks for your patience — anything else I can help with?', p_owner_id::text, v_now),
    (gen_random_uuid(), p_license_id, 'chat', 'hours',
     'Our team is available Monday to Friday, 9am–6pm.', p_owner_id::text, v_now);

  INSERT INTO tags (id, license_id, name, author_id)
  VALUES
    (gen_random_uuid(), p_license_id, 'question', p_owner_id::text),
    (gen_random_uuid(), p_license_id, 'lead', p_owner_id::text);

  -- A sample visitor. Email left null — an anonymous visitor is realistic and
  -- avoids any collision with a real customer the owner later adds.
  INSERT INTO customers (id, organization_id, name, is_lead, last_activity_at)
  VALUES (v_customer, p_organization_id, 'Sample visitor', false, v_now);

  -- One live conversation, assigned to the owner so it shows in their inbox
  -- immediately — the owner's token is unrestricted, so no team access is needed.
  INSERT INTO chats (id, license_id, customer_id, active, created_at)
  VALUES (p_chat_id, p_license_id, v_customer, true, v_started);

  INSERT INTO chat_users (chat_id, user_id, user_type, present, joined_at)
  VALUES
    (p_chat_id, v_customer::text, 'customer', true, v_started),
    (p_chat_id, p_owner_id::text, 'agent', true, v_started);

  INSERT INTO threads
    (id, chat_id, license_id, active, assignee_id, event_sequence, first_response_at, created_at)
  VALUES
    (p_thread_id, p_chat_id, p_license_id, true, p_owner_id, 3,
     v_started + INTERVAL '2 minutes', v_started);

  INSERT INTO events
    (id, thread_id, chat_id, license_id, type, text, author_id, author_type, recipients, created_at)
  VALUES
    (p_thread_id || '_1', p_thread_id, p_chat_id, p_license_id, 'message',
     'Hi! This is a sample conversation so your inbox is not empty.',
     v_customer::text, 'customer', 'all', v_started),
    (p_thread_id || '_2', p_thread_id, p_chat_id, p_license_id, 'message',
     'Try the saved replies with # in the composer, and archive this chat when you are done.',
     p_owner_id::text, 'agent', 'all', v_started + INTERVAL '2 minutes'),
    (p_thread_id || '_3', p_thread_id, p_chat_id, p_license_id, 'message',
     'Thanks — this looks great!',
     v_customer::text, 'customer', 'all', v_started + INTERVAL '4 minutes');

  UPDATE licenses SET demo_seeded_at = v_now WHERE id = p_license_id;

  RETURN QUERY SELECT true, 3, 2, 1, 1;
END;
$$;

REVOKE EXECUTE ON FUNCTION onboarding_seed_demo(BIGINT, UUID, UUID, TEXT, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION onboarding_seed_demo(BIGINT, UUID, UUID, TEXT, TEXT) TO nexa_app;
